---
#http://kalevala.finlit.fi/erisnimet
computername: Tuuri
hostname: tuuri

is_music_computer: yes

finder_proxy_icon_hover_delay: 0

safari_show_full_url_in_address_bar: true
safari_open_safe_files_automatically: true
safari_show_status_bar: true
safari_show_developer_menu: true

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /bin/zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_apps:
  - basictex
  - chrome
  - discord
  - docker
  - font-fira-code
  - font-hack
  - font-hasklig
  - font-jetbrains-mono
  - google-chrome
  - slack
  - spotify
  - tableplus
  - tor-browser
  - transmission
  - tunnelblick
  - visual-studio-code
  - whatsapp
  - zotero
  - dropbox
# vlc, sourcetree, twitch, telegram

homebrew_packages:
  - awscli
  - curl
  - ffmpeg
  - git
  - imagemagick
  - make
  - mas
  - openssh
  - poetry
  - pyenv
  - r
  - tmux
  - transmission-cli
  - vim
  - wget
  - yadm

homebrew_music_packages:
  - native-access

mas_apps:
  - { name: Ghostery, id: 1436953057 }
  - { name: Unsplash Wallpapers, id: 1284863847 }
  - { name: Coin Tick, id: 1141688067}
  - { name: Xcode, id: 497799835}
  #- { name: Patterns, id: 429449079 }
  #- { name: 1Blocker, id: 1107421413 }
  #- { name: Bear, id: 1091189122 }
  #- { name: Slack, id: 803453959}
  #- { name: Telegram, id: 747648890}
  #- { name: Whatsapp, id: 1147396723}
