---

- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3


  pre_tasks:
    - name: Include configuration
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - config.yml
          skip: true
      tags: ['always']

  roles:
    - role: homebrew
      tags: [homebrew]
    - role: mas
      tags: [mas]
    - role: settings
      tags: [settings]
    - role: terminal
