---
- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Setup .zshrc
  template:
    src: zshrc.j2
    dest: '~/.zshrc'
    backup: yes
    mode: 'u=rw,go=r'

- name: Copy terminal colors
  template:
    src: default.terminal.j2
    dest: ~/.default.terminal
